import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PRIA Generated App',
  description: 'A PRIA-compliant Next.js application generated by Claude Code SDK',
  keywords: ['PRIA', 'Next.js', 'Supabase', 'Multi-tenant', 'Enterprise'],
  authors: [{ name: 'PRIA AI' }],
  creator: 'Claude Code SDK',
  publisher: 'PRIA Platform',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: process.env.NEXT_PUBLIC_APP_URL,
    title: 'PRIA Generated App',
    description: 'A PRIA-compliant Next.js application generated by Claude Code SDK',
    siteName: 'PRIA Generated App',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'PRIA Generated App',
    description: 'A PRIA-compliant Next.js application generated by Claude Code SDK',
    creator: '@pria_ai',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#3b82f6" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <div id="root">
          <main className="min-h-screen bg-background text-foreground">
            {children}
          </main>
        </div>
        {/* Development mode indicator */}
        {process.env.NODE_ENV === 'development' && (
          <div className="fixed bottom-4 right-4 z-50">
            <div className="bg-orange-500 text-white px-3 py-1 rounded-full text-xs font-mono">
              PRIA DEV
            </div>
          </div>
        )}
      </body>
    </html>
  )
}