# This is a config for E2B sandbox template.
# You can use template ID (bslm087lozmkvjz6nwle) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("bslm087lozmkvjz6nwle") # Sync sandbox
# sandbox = await AsyncSandbox.create("bslm087lozmkvjz6nwle") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bslm087lozmkvjz6nwle')

team_id = "d9ae965a-2a35-4a01-bc6e-6ff76faaa12c"
dockerfile = "e2b.Dockerfile"
template_id = "bslm087lozmkvjz6nwle"
