# This is a config for E2B sandbox template.
# You can use template ID (33mz2agmad58ip0izxbc) or template name (claude-code-e2b-20250724-104042) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("claude-code-e2b-20250724-104042") # Sync sandbox
# sandbox = await AsyncSandbox.create("claude-code-e2b-20250724-104042") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('claude-code-e2b-20250724-104042')

team_id = "d9ae965a-2a35-4a01-bc6e-6ff76faaa12c"
dockerfile = "e2b.Dockerfile"
template_name = "claude-code-e2b-20250724-104042"
template_id = "33mz2agmad58ip0izxbc"
