import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { CheckCircle2, Code2, Database, Shield, Zap, ArrowRight } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-6xl">
      {/* Header Section */}
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 mb-4">
          <div className="h-8 w-8 rounded-full pria-gradient flex items-center justify-center">
            <Code2 className="h-4 w-4 text-white" />
          </div>
          <Badge variant="secondary" className="text-sm font-medium">
            PRIA Generated Application
          </Badge>
        </div>
        
        <h1 className="text-4xl font-bold tracking-tight mb-4">
          Welcome to your PRIA App
        </h1>
        
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
          This is a production-ready Next.js application generated by the PRIA platform 
          with enterprise-grade security, multi-tenancy, and compliance built-in.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button size="lg" className="pria-button-primary">
            Get Started
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
          <Button variant="outline" size="lg">
            View Documentation
          </Button>
        </div>
      </div>

      {/* Features Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
        <Card className="pria-card">
          <CardHeader>
            <Shield className="h-8 w-8 text-blue-600 mb-2" />
            <CardTitle>Enterprise Security</CardTitle>
            <CardDescription>
              Built with workspace isolation, RLS policies, and secure authentication patterns
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Row-Level Security (RLS)
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Workspace Tenancy
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Supabase Authentication
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card className="pria-card">
          <CardHeader>
            <Database className="h-8 w-8 text-green-600 mb-2" />
            <CardTitle>Modern Stack</CardTitle>
            <CardDescription>
              Next.js 15, React 19, TypeScript, Tailwind CSS, and Supabase
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Next.js 15 App Router
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                TypeScript Strict Mode
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                shadcn/ui Components
              </li>
            </ul>
          </CardContent>
        </Card>

        <Card className="pria-card">
          <CardHeader>
            <Zap className="h-8 w-8 text-purple-600 mb-2" />
            <CardTitle>Production Ready</CardTitle>
            <CardDescription>
              Deployment-ready with monitoring, testing, and performance optimization
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Comprehensive Testing
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Performance Optimized
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-600" />
                Mobile Responsive
              </li>
            </ul>
          </CardContent>
        </Card>
      </div>

      <Separator className="my-12" />

      {/* Development Status */}
      <div className="text-center">
        <Card className="max-w-2xl mx-auto">
          <CardHeader>
            <CardTitle className="flex items-center justify-center gap-2">
              <Code2 className="h-5 w-5" />
              Development Status
            </CardTitle>
            <CardDescription>
              This application was generated by the PRIA platform and is ready for customization
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-center gap-4 text-sm">
              <Badge variant="outline">Phase 1: Requirements ✓</Badge>
              <Badge variant="outline">Phase 2: Architecture ✓</Badge>
              <Badge variant="outline">Phase 3: Planning ✓</Badge>
              <Badge variant="outline">Phase 4: Development ✓</Badge>
            </div>
            
            <p className="text-sm text-muted-foreground">
              Generated by Claude Code SDK using PRIA compliance standards.
              All code follows enterprise security patterns and multi-tenant architecture.
            </p>
            
            <div className="flex justify-center pt-4">
              <Button variant="outline" size="sm">
                View Project Specification
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Footer */}
      <div className="text-center mt-12 pt-8 border-t">
        <p className="text-sm text-muted-foreground">
          Built with ❤️ by{' '}
          <a href="https://pria.ai" className="font-medium text-blue-600 hover:underline">
            PRIA Platform
          </a>
          {' '}using Claude Code SDK
        </p>
      </div>
    </div>
  )
}