version: '3.8'

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      # Exclude .next folder to avoid conflicts
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      # Enable hot reload in Docker
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # Daytona-specific environment
      - DAYTONA_ENV=true
      # Allow external API access
      - HOSTNAME=0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - dev-network
    # Health check for Daytona monitoring
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Restart policy for stability
    restart: unless-stopped

networks:
  dev-network:
    driver: bridge 